### ISSUE TITLE
Why in the world is this program described as a GUI application?

### ISSUE THREAD

**Issue by ghost** [timlegrand/giterm#13]
The program clearly uses a TUI.
TUI is different from CLI.

**Comment by timlegrand** [comment]
Hi, this program is not described as a GUI application.
The first line of the `README.rst` file says _Giterm is a ncurses-based terminal GUI for Git_.
Though I agree that GUI would be an abusive term for Giterm, it seems that "terminal-based GUI" _is_ an acceptable definition for such a rich _TUI_ (this is not a simple TUI but a _GUI-like_ TUI).
Moreover there is no intention to lie about Giterm's nature:

1. in addition to the README file, its Pypi's `long_description` tells the same
2. the Pypi classifiers explicit `Environment :: Console :: Curses`
3. there is a screenshot on the project's home page.

Please feel free to suggest an improvement if you have any, but take care not to make an opinion picking a single word in a full-text. I would also recommend not starting your GitHub experience by attacking projects before having carefully read their description.
